---
- hosts: all
  become: true
  pre_tasks:


    - name: install updates (Fedora)
      package:
         update_only: yes
         update_cache: yes
      when: ansible_distribution == "Fedora"
    - name: install updates (Ubuntu)
      apt:
         upgrade: dist
         update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root
  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKw72Oqbtke0jSn6In36Izq9SCJKtuEQ8TewAMpmDOyK darkreskin@reese-Vm"

  - name: sudoers file for simone
    tags: always
    copy: 
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440




- hosts: web_server
  become: true
  tasks:

    - name: Install Apache and PHP for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Ensure python3-libdnf5 is installed (Fedora)
      raw: dnf install -y python3-libdnf5 python3-dnf
      when: ansible_facts['distribution'] == "Fedora"
      register: dnf_install
      changed_when: "'Nothing to do' not in dnf_install.stdout"
    - name: Install Apache and PHP for Fedora servers
      package:
        name:
          - httpd
          - php
        state: latest
      when: ansible_facts['distribution'] == "Fedora"
    
    - name: Start httpd (Fedora)
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

      when: ansible_distribution == "Fedora"

    
- hosts: db_server
  become: true
  tasks:

    - name: Install Mariadb (Ubuntu)
      apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: copy default html file
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
